# TODO

ID = int
Address = int

UPDATE = "UPDATE"
INCOMING_PLANE = "INCOMING_PLANE"
INCOMING_INFO = "INCOMING_INFO"
SECTOR_DISTANCE = 20

LOST_PLANE = "LOST_PLANE"
TOO_MANY_PLANES = "TOO_MANY_PLANES"
PLANE_WITHOUT_INFO = "PLANE_WITHOUT_INFO"

SERVER_ADDRESS = 8000
UPDATE_TIME = 5